[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    'ignore:jsonschema.RefResolver is deprecated:DeprecationWarning',
    'ignore:jsonschema.exceptions.RefResolutionError is deprecated:DeprecationWarning',
    'ignore:Accessing jsonschema.draft4_format_checker is deprecated:DeprecationWarning',
]